### ISSUE TITLE
package.json is created for libraries that are not buildable/publishable 

### ISSUE THREAD

**Issue by rohanraj07** [angular-architects/nx-ddd-plugin#22]

**Comment by pascalbe-dev** [comment]
@rohanraj07 
Is this still happening? I can not reproduce this behavior. 

Keep in mind, that libs are buildable by default. If do not want to have them buildable, you have to override the type. 
e.g. like this:

`ng generate @angular-architects/ddd:domain --name=booking --type=internal`

**Comment by dragonflypl** [comment]
Can you please update documentation / readme so that it describes this `type` ? I also used to create libraries that are not buildable and wanted to use `--buildable=false` instead

**Comment by pascalbe-dev** [comment]
Yea, this could be documented since it behaves differently than the nrwl schematics. 
Still, just as a reminder, you can always check the available options via: `nx g @angular-architects/ddd:ui --help` or via the Nx Console (if you use it). Not sure, if it makes sense to document every single option, that can be passed to the schematic.

**Comment by manfredsteyer** [comment]
This is solved by version 2.0.0
