### ISSUE TITLE
[Question] Why disable Ivy in all tsconfig.lib.prod.json?

### ISSUE THREAD

**Issue by HymanZHAN** [angular-architects/nx-ddd-plugin#30]
Sorry if this is a dumb question. I am just getting to learn about Angular libs.

I found that if I just use the nx cli command `nx g @nrwl/angular:lib ui` the created library doesn't contain this `tsconfig.lib.prod.json` file. So my questions are:

- What's the use of it? 
- Is it for publishing the lib to npm? 
- Will disabling Ivy affect the performance and bundle size of the lib?

Thanks!

**Comment by pascalbe-dev** [comment]
Hi, 
i can share my thoughts on some of your questions. Maybe it helps. 

* What's the use of the tsconfig.lib.prod.json?
By default, libs generated via the nrwl schematic are not "buildable" or "publishable". This means, they do not contain any target to build them. They are only built, when another workspace project (like an app), which uses the libs, is built. This works fine for many use cases. However, if you have a lot of apps and they all reference the lib, then the lib is built multiple times. To avoid this, one can pass a buildable flag to the schematic, which then adds a build target to the lib workspace project configuration. This then enables incremental builds. Read more [here](https://nx.dev/latest/angular/guides/ci/incremental-builds) or [here](https://nx.dev/latest/angular/workspace/structure/buildable-and-publishable-libraries).


This ddd plugin makes libraries (feature, domain, ...) buildable by default. That's why you have this file for libs generated via the nx ddd plugin and not for libs generated via the nrwl angular library schematic. 
If you, however, do not want to have buildable libs, you can also pass the type option set to "internal" for any of the nx ddd schematics. 

* Is it for publishing libs to npm?
Since the libs are buildable and not publishable by default, they are not meant to be published to npm. However, you can use the publishable type. In that case, you have a different builder for the build target in your library. This builder packages your lib so that it can then be published to npm.

Regarding your last question - i do not know. The only thing I can say is that nx recommends to not enable ivy for publishable libs. See [here](https://github.com/nrwl/nx/blob/master/packages/angular/src/schematics/library/schema.json). 


I hope, this helped a bit 🤓

**Comment by HymanZHAN** [comment]
@pascalbe-dev Thank you! It really helps. I will sure dive deeper into the nx docs and learn more about it.

About Ivy, it's now[ allowed to use it in buildable libs](https://github.com/nrwl/nx/commit/090350b) but still not recommended in publishable libs. From [Angular's doc](https://angular.io/guide/creating-libraries#publishing-your-library):

> For now, it is not recommended to publish Ivy libraries to NPM because Ivy generated code is not backward compatible with View Engine, so apps using View Engine will not be able to consume them. Furthermore, the internal Ivy instructions are not yet stable, which can potentially break consumers using a different Angular version from the one used to build the library.
> 
> When a published library is used in an Ivy app, the Angular CLI will automatically convert it to Ivy using a tool known as the Angular compatibility compiler (ngcc). Thus, publishing your libraries using the View Engine compiler ensures that they can be transparently consumed by both View Engine and Ivy apps.
