### ISSUE TITLE
Have questions about libNameAndDirectory?

### ISSUE THREAD

**Issue by zhangjindong** [angular-architects/nx-ddd-plugin#79]
https://github.com/angular-architects/nx-ddd-plugin/blob/f9414527aa5372c1058af79d13bf3ea8e4f746fa/libs/ddd/src/schematics/domain/index.ts#L36

Why is `${libName}/${options.directory}`
Instead of `${options.directory}/${libName}`
I think Domain is unique, which means that Domain/Directory can only have one directory.

We might need something like this:
libs/management/user/domain
libs/management/user/feature-**
libs/management/dept/domain
libs/management/dept/featue-**

Did I understand it wrong?

**Comment by cogoo** [comment]
I think this is a bug, I've resorted to switching the names around to get my desired output

**Comment by sg-gdarnell** [comment]
I think you're correct. This command:

> ng g @angular-architects/ddd:domain user --directory=management

Generates `libs/user/management/domain` instead of `libs/management/user/domain`

I think this is incorrect, given that it's inconsistent with the `directory` in vanilla nx generators, and given that it's inconsistent with the `appDirectory` in the same command just a few lines above in the same file:

https://github.com/angular-architects/nx-ddd-plugin/blob/f9414527aa5372c1058af79d13bf3ea8e4f746fa/libs/ddd/src/schematics/domain/index.ts#L24
